name: Bioinformatics Pipeline CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
            uses: actions/checkout@v2

        - name: Set up Docker
            uses: docker/setup-buildx-action@v1

        - name: Build Docker image
            run: docker build -t bioinformatics-pipeline .

        - name: Run pipeline script
            run: docker run bioinformatics-pipeline
FROM ubuntu:20.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
  samtools \
  wget \
  curl \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

# Install udocker
RUN pip3 install udocker

# Add your script to the Docker image
COPY scripts/run_pipeline.sh /usr/local/bin/run_pipeline.sh

# Make the script executable
RUN chmod +x /usr/local/bin/run_pipeline.sh

# Set the entrypoint to your script
ENTRYPOINT ["run_pipeline.sh"]
